### ISSUE TITLE
how to setup the value "int16_t example_element[]"

### ISSUE THREAD

**Issue by Shawn-115200** [alibukharai/Blogs#1]
in this file "Blogs/ESP-DL/model_deployment/main/app_main.cpp",
how to setup the value "int16_t example_element[]"

**Comment by alibukharai** [comment]
> 

https://github.com/alibukharai/Blogs/blob/24d48d8e99669676067d0f7a9d27f1593d9b75ef/ESP-DL/model_deployment/main/app_main.cpp#L17
Check this out. The values are 96*96 pixel values.
