### ISSUE TITLE
No url found for submodule path 'Activity_detection/model_deployment/components/esp-dl' in .gitmodules

### ISSUE THREAD

**Issue by snail0815** [alibukharai/Blogs#2]
git submodule update --init --recursive
fatal: No url found for submodule path 'Activity_detection/model_deployment/components/esp-dl' in .gitmodules

**Comment by alibukharai** [comment]
Please follow these steps [https://github.com/alibukharai/Blogs/tree/main/Activity_detection#steps-to-download-and-run](url)

**Comment by alibukharai** [comment]
I have updated the .gitmodules files. please try again
