### ISSUE TITLE
no print in monitor

### ISSUE THREAD

**Issue by togethf** [alibukharai/Blogs#6]
Sorry, i'm a newer.I just downloaded the code, and execute `idf.py set-target esp32s3` and `idf.py flash -p com6 monitor`.But in the monitor, i didn't get anything.The output is below:
`--- idf_monitor on com6 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x1828
load:0x403c9700,len:0xe6c
load:0x403cc700,len:0x2ff0
entry 0x403c997c
I (24) boot: ESP-IDF v4.4.7-dirty 2nd stage bootloader
I (25) boot: compile time 21:54:21
I (25) boot: Multicore bootloader
I (27) boot: chip revision: v0.2
I (31) qio_mode: Enabling default flash chip QIO
I (36) boot.esp32s3: Boot SPI Speed : 80MHz
I (41) boot.esp32s3: SPI Mode       : QIO
I (46) boot.esp32s3: SPI Flash Size : 8MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 factory          factory app      00 00 00010000 003c0000
I (74) boot:  1 nvs              WiFi data        01 02 003d0000 00004000
I (82) boot:  2 fr               Unknown data     01 06 003e0000 00020000
I (89) boot: End of partition table
I (93) esp_image: segment 0: paddr=00010020 vaddr=3c050020 size=1a37ch (107388) map
I (118) esp_image: segment 1: paddr=0002a3a4 vaddr=3fc91a20 size=02434h (  9268) load
I (120) esp_image: segment 2: paddr=0002c7e0 vaddr=40374000 size=03838h ( 14392) load
I (127) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=407f4h (264180) map
I (172) esp_image: segment 4: paddr=0007081c vaddr=40377838 size=0a1e4h ( 41444) load
I (186) boot: Loaded app from partition at offset 0x10000
I (186) boot: Disabling RNG early entropy source...
I (186) cpu_start: Multicore app
I (190) opi psram: vendor id : 0x0d (AP)
I (195) opi psram: dev id    : 0x02 (generation 3)
I (200) opi psram: density   : 0x03 (64 Mbit)
I (205) opi psram: good-die  : 0x01 (Pass)
I (210) opi psram: Latency   : 0x01 (Fixed)
I (215) opi psram: VCC       : 0x01 (3V)
I (219) opi psram: SRF       : 0x01 (Fast Refresh)
I (225) opi psram: BurstType : 0x01 (Hybrid Wrap)
I (230) opi psram: BurstLen  : 0x01 (32 Byte)
I (235) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (241) opi psram: DriveStrength: 0x00 (1/1)
I (247) MSPI Timing: PSRAM timing tuning index: 5
I (252) spiram: Found 64MBit SPI RAM device
I (256) spiram: SPI RAM mode: sram 80m
I (261) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (268) cpu_start: Pro cpu up.
I (272) cpu_start: Starting app cpu, entry point is 0x40375308
0x40375308: call_start_cpu1 at F:/Espressif-4.4.7/frameworks/esp-idf-v4.4.7/components/esp_system/port/cpu_start.c:151`
I don't know why there is no print, can you help me ?

**Comment by alibukharai** [comment]
You have to change few settings from Menuconfig I forget what exactly the settings are. If not found those settigns: I recommand to use an external JTAG to view the logs.
