### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by Engr-Muhammad-Anas** [alibukharai/Blogs#7]
In Repo: Activity_Detection/model_deployment/components, there was an error in downloading esp-dl and esp-who files. Pls upload these files again.

**Comment by alibukharai** [comment]
Please follow this method. 
https://github.com/alibukharai/Blogs/tree/main/ESP-DL#1-clone-the-git-hub-repository

**Comment by Engr-Muhammad-Anas** [comment]
Jazakallah
